// Code generated by protoc-gen-go-grpc. DO NOT EDIT manually.
// Source: proto/agent.proto
package agentpb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---- Message types ----

type AgentEvent struct {
	AgentId    string `json:"agent_id"`
	AgentToken string `json:"agent_token"`
	// Payload is one of the following
	Payload isAgentEvent_Payload
}

type isAgentEvent_Payload interface{ isAgentEvent_Payload() }

type AgentEvent_Connected struct{ Connected *AgentConnected }
type AgentEvent_Health struct{ Health *AgentHealth }
type AgentEvent_BackupStarted struct{ BackupStarted *BackupStarted }
type AgentEvent_BackupProgress struct{ BackupProgress *BackupProgress }
type AgentEvent_BackupCompleted struct{ BackupCompleted *BackupCompleted }
type AgentEvent_BackupFailed struct{ BackupFailed *BackupFailed }
type AgentEvent_RestoreStarted struct{ RestoreStarted *RestoreStarted }
type AgentEvent_RestoreCompleted struct{ RestoreCompleted *RestoreCompleted }
type AgentEvent_RestoreFailed struct{ RestoreFailed *RestoreFailed }

func (*AgentEvent_Connected) isAgentEvent_Payload()      {}
func (*AgentEvent_Health) isAgentEvent_Payload()         {}
func (*AgentEvent_BackupStarted) isAgentEvent_Payload()  {}
func (*AgentEvent_BackupProgress) isAgentEvent_Payload() {}
func (*AgentEvent_BackupCompleted) isAgentEvent_Payload(){}
func (*AgentEvent_BackupFailed) isAgentEvent_Payload()   {}
func (*AgentEvent_RestoreStarted) isAgentEvent_Payload() {}
func (*AgentEvent_RestoreCompleted) isAgentEvent_Payload(){}
func (*AgentEvent_RestoreFailed) isAgentEvent_Payload()  {}

type AgentConnected struct {
	Hostname string
	Version  string
	Os       string
}

type AgentHealth struct {
	Healthy        bool
	CpuPercent     float64
	MemoryPercent  float64
	DiskPercent    float64
}

type BackupStarted   struct{ RunId, JobId string }
type BackupProgress  struct {
	RunId           string
	BytesRead       int64
	BytesCompressed int64
	BytesUploaded   int64
	Percent         float64
}
type BackupCompleted struct {
	RunId           string
	BytesRead       int64
	BytesCompressed int64
	BytesUploaded   int64
	Checksum        string
	StoragePath     string
}
type BackupFailed     struct{ RunId, Error string }
type RestoreStarted   struct{ RestoreId string }
type RestoreCompleted struct{ RestoreId string }
type RestoreFailed    struct{ RestoreId, Error string }

type ServerCommand struct {
	Command isServerCommand_Command
}

type isServerCommand_Command interface{ isServerCommand_Command() }

type ServerCommand_RunBackup    struct{ RunBackup *RunBackupCommand }
type ServerCommand_CancelBackup struct{ CancelBackup *CancelBackupCommand }
type ServerCommand_StartRestore struct{ StartRestore *StartRestoreCommand }
type ServerCommand_GetStatus    struct{ GetStatus *GetStatusCommand }

func (*ServerCommand_RunBackup) isServerCommand_Command()    {}
func (*ServerCommand_CancelBackup) isServerCommand_Command() {}
func (*ServerCommand_StartRestore) isServerCommand_Command() {}
func (*ServerCommand_GetStatus) isServerCommand_Command()    {}

type RunBackupCommand    struct{ RunId, JobId string }
type CancelBackupCommand struct{ RunId string }
type StartRestoreCommand struct {
	RestoreId, BackupRunId, DestinationPath, TargetDatabase string
}
type GetStatusCommand struct{}

type ProgressRequest struct {
	AgentId         string
	AgentToken      string
	RunId           string
	BytesRead       int64
	BytesCompressed int64
	BytesUploaded   int64
	Percent         float64
	Status          string
	Error           string
	Checksum        string
	StoragePath     string
}
type ProgressResponse struct{ Accepted bool }

type JobConfigRequest struct {
	AgentId    string
	AgentToken string
	JobId      string
}
type JobConfigResponse struct {
	JobId            string
	SourceType       string
	SourcePath       string
	SourceDatabase   string
	IncludePatterns  string
	ExcludePatterns  string
	Mode             string
	Encrypted        bool
	CronExpr         string
	StorageType      string
	StorageBucket    string
	StorageRegion    string
	StorageEndpoint  string
	StorageAccessKey string
	StorageSecretKey string
	StoragePath      string
}

// ---- gRPC service interfaces ----

const (
	AgentService_Connect_FullMethodName        = "/backup.agent.v1.AgentService/Connect"
	AgentService_ReportProgress_FullMethodName = "/backup.agent.v1.AgentService/ReportProgress"
	AgentService_GetJobConfig_FullMethodName   = "/backup.agent.v1.AgentService/GetJobConfig"
)

type AgentServiceServer interface {
	Connect(AgentService_ConnectServer) error
	ReportProgress(context.Context, *ProgressRequest) (*ProgressResponse, error)
	GetJobConfig(context.Context, *JobConfigRequest) (*JobConfigResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(AgentService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) ReportProgress(context.Context, *ProgressRequest) (*ProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedAgentServiceServer) GetJobConfig(context.Context, *JobConfigRequest) (*JobConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobConfig not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

type AgentService_ConnectServer interface {
	Send(*ServerCommand) error
	Recv() (*AgentEvent, error)
	grpc.ServerStream
}

type agentServiceConnectServer struct{ grpc.ServerStream }

func (x *agentServiceConnectServer) Send(m *ServerCommand) error {
	return x.ServerStream.SendMsg(m)
}
func (x *agentServiceConnectServer) Recv() (*AgentEvent, error) {
	m := new(AgentEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backup.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportProgress",
			Handler:    _AgentService_ReportProgress_Handler,
		},
		{
			MethodName: "GetJobConfig",
			Handler:    _AgentService_GetJobConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&agentServiceConnectServer{stream})
}

func _AgentService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: AgentService_ReportProgress_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportProgress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetJobConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetJobConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: AgentService_GetJobConfig_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetJobConfig(ctx, req.(*JobConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}
